### ISSUE TITLE
Long lines in .scrbl source

### ISSUE THREAD

**Issue by LiberalArtist** [mlemmer/DigitalHumanities#3]
While preparing https://github.com/mlemmer/DigitalHumanities/pull/2, I noticed that (at least some of) the Scribble files seem to be one paragraph for line, meaning they have very long lines (perhaps with the expectation that the file would be read with word-wrap on?). I think it would be worth-while to split these lines up, perhaps to around or at least closer to the 102 characters suggested by the [style guide](http://docs.racket-lang.org/style/Textual_Matters.html#%28part._.Line_.Width%29), for several reasons:

1. Word-wrap doesn't seem to be on by default for `.scrbl` files (at least, it isn't for me: tbh I don't think I've ever looked for word-wrap in DrRacket), so these are hard to read.
2. In a tutorial context specifically, a novice looking at the code might incorrectly think that Scribble uses line-breaks rather than blank lines to delimit paragraphs.
3. Such long lines make git diffs hard to read.
4. To whatever extent one can draw a rule from widespread practice, the de facto standard style for Scribble documents certainly seems to be to manually break lines at a reasonable length.

I'd be happy to make a pull request for this if you're persuaded!

**Comment by mlemmer** [comment]
Thank you for submitting the pull request and for identifying the issue. I'm still new to all of this.
